/*******************************************************************************
*
* Header file generated by RDP on Oct 31 2005 17:42:55 from gtb.bnf
*
*******************************************************************************/
#ifndef GTB_H
#define GTB_H

#include "arg.h"
#include "graph.h"
#include "hist.h"
#include "memalloc.h"
#include "scan.h"
#include "set.h"
#include "symbol.h"
#include "textio.h"


/* Maximum number of passes */
#define RDP_PASSES 2

/* Time and date stamp */
#define RDP_STAMP "Generated on Oct 31 2005 17:42:55 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_34 /* " */ = SCAN_P_TOP,RDP_T_35 /* # */,RDP_T_36 /* $ */,RDP_T_3661 /* $= */,RDP_T_37 /* % */,RDP_T_3761 /* %= */,RDP_T_38 /* & */,RDP_T_3861 /* &= */,
RDP_T_39 /* ' */,RDP_T_40 /* ( */,RDP_T_4042 /* (* */,RDP_T_41 /* ) */,RDP_T_42 /* * */,RDP_T_4242 /* ** */,RDP_T_424261 /* **= */,RDP_T_4261 /* *= */,
RDP_T_43 /* + */,RDP_T_4361 /* += */,RDP_T_45 /* - */,RDP_T_4561 /* -= */,RDP_T_46 /* . */,RDP_T_47 /* / */,RDP_T_4761 /* /= */,RDP_T_58 /* : */,
RDP_T_5858 /* :: */,RDP_T_585861 /* ::= */,RDP_T_5861 /* := */,RDP_T_60 /* < */,RDP_T_6060 /* << */,RDP_T_606061 /* <<= */,RDP_T_6061 /* <= */,RDP_T_6062 /* <> */,
RDP_T_61 /* = */,RDP_T_6136 /* =$ */,RDP_T_6137 /* =% */,RDP_T_6138 /* =& */,RDP_T_6142 /* =* */,RDP_T_614242 /* =** */,RDP_T_6143 /* =+ */,RDP_T_6145 /* =- */,
RDP_T_6147 /* =/ */,RDP_T_6160 /* =< */,RDP_T_616060 /* =<< */,RDP_T_6161 /* == */,RDP_T_6162 /* => */,RDP_T_616262 /* =>> */,RDP_T_61124 /* =| */,RDP_T_62 /* > */,
RDP_T_6261 /* >= */,RDP_T_6262 /* >> */,RDP_T_626261 /* >>= */,RDP_T_63 /* ? */,RDP_T_64 /* @ */,RDP_T_91 /* [ */,RDP_T_9142 /* [* */,RDP_T_93 /* ] */,
RDP_T_96 /* ` */,RDP_T_124 /* | */,RDP_T_12461 /* |= */,RDP_T_126 /* ~ */,
RDP_TT_TOP
};

/* Tree data types */

typedef struct rdp_tree_node_data_struct
{
  SCAN_DATA
   struct script_symbols_data* symbol_table_entry; int tilde:1; 
} rdp_tree_node_data;
typedef struct rdp_tree_edge_data_struct
{
  int rdp_edge_kind;
   /* No edge data */ 
} rdp_tree_edge_data;

/* Symbol table support */
/* Parser start production */
void text(rdp_tree_node_data* rdp_tree);



#endif

/* End of gtb.h */
